In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import glob
import requests
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import time
import re

# encoding='cp949'

In [209]:
df = pd.read_csv('/python/project/Seoulscore_naver.csv')
df

,Unnamed: 0,업종,업소명,주요품목,가격,연락처,주소,수정주소,검색어,별점
0,0,한식_육류,신원식당,삼겹살,16000원,02-3394-5121,"서울특별시 동대문구 장한로 92, 101호 (장안동, 화성빌딩)","서울특별시 동대문구 장한로 92, 101호 (장안동, 화성빌딩)",서울특별시 동대문구 신원식당,별점\n4.78
1,1,한식_일반,신미가 맛집,한식부페,7000원,0507-1366-1326,서울특별시 은평구 서울특별시 은평구 증산로15길 24-1,서울특별시 은평구 증산로15길 24-1,서울특별시 은평구 신미가 맛집,방문자리뷰 32
2,2,한식_일반,북한산 손칼국수,손칼국수,5500원,0507-1407-4413,서울특별시 은평구 서울특별시 은평구 대서문길36,서울특별시 은평구 대서문길36,서울특별시 은평구 북한산 손칼국수,별점\n4.32
3,3,한식_일반,응암칼국수,삼겹순대국,8000원,02-918-6700,서울특별시 은평구 서울특별시 은평구 응암로21길 18-1,서울특별시 은평구 응암로21길 18-1,서울특별시 은평구 응암칼국수,별점\n4.35
4,4,한식_일반,따뜻한 밥상,김치찌개,3000원,02-000-0000,"서울특별시 은평구 서울특별시 은평구 연서로 260, 2층","서울특별시 은평구 연서로 260, 2층",서울특별시 은평구 따뜻한 밥상,방문자리뷰 280
...,...,...,...,...,...,...,...,...,...,...
1017,1017,한식_일반,시골청국장,청국장,8000원,02-548-0171,서울특별시 강남구 학동로 504 서울빌딩 101호,서울특별시 강남구 학동로 504 서울빌딩 101호,서울특별시 강남구 시골청국장,별점\n4.47
1018,1018,한식_일반,해남식당,청국장,8000원,02-543-9660,서울특별시 강남구 학동로101길 26 청담삼익상가 지하1층 4호,서울특별시 강남구 학동로101길 26 청담삼익상가 지하1층 4호,서울특별시 강남구 해남식당,별점\n4.39
1019,1019,한식_일반,지리산,닭곰탕,9000원,02-546-3127,서울특별시 강남구 학동로43길 7 지상1층,서울특별시 강남구 학동로43길 7 지상1층,서울특별시 강남구 지리산,별점\n4.18
1020,1020,이미용업,선경헤어샵,커트,12000원,02-566-3019,서울특별시 강남구 삼성로 151 선경상가 지하1층 13호,서울특별시 강남구 삼성로 151 선경상가 지하1층 13호,서울특별시 강남구 선경헤어샵,방문자리뷰 4
1021,1021,한식_육류,청송숯불화로구이,돼지갈비(250g),20000원,02-549-3739,서울특별시 강남구 언주로 114길 17,서울특별시 강남구 언주로 114길 17,서울특별시 강남구 청송숯불화로구이,별점\n4.52

In [39]:
print(df['주소'].dtype)

object

In [210]:
df['별점']

0        별점\n4.78
1        방문자리뷰 32
2        별점\n4.32
3        별점\n4.35
4       방문자리뷰 280
          ...
1017     별점\n4.47
1018     별점\n4.39
1019     별점\n4.18
1020      방문자리뷰 4
1021     별점\n4.52
Name: 별점, Length: 1022, dtype: object

In [222]:
df2 = df[df['별점'].str.contains('별점\n')]
df2

,Unnamed: 0,업종,업소명,주요품목,가격,연락처,주소,수정주소,검색어,별점
0,0,한식_육류,신원식당,삼겹살,16000원,02-3394-5121,"서울특별시 동대문구 장한로 92, 101호 (장안동, 화성빌딩)","서울특별시 동대문구 장한로 92, 101호 (장안동, 화성빌딩)",서울특별시 동대문구 신원식당,별점\n4.78
2,2,한식_일반,북한산 손칼국수,손칼국수,5500원,0507-1407-4413,서울특별시 은평구 서울특별시 은평구 대서문길36,서울특별시 은평구 대서문길36,서울특별시 은평구 북한산 손칼국수,별점\n4.32
3,3,한식_일반,응암칼국수,삼겹순대국,8000원,02-918-6700,서울특별시 은평구 서울특별시 은평구 응암로21길 18-1,서울특별시 은평구 응암로21길 18-1,서울특별시 은평구 응암칼국수,별점\n4.35
11,11,중식,서희,자장면(현금),4500원,02-2212-8877,"서울특별시 동대문구 사가정로23길 64, 105-101 (장안동, 성우스타팰리스)","서울특별시 동대문구 사가정로23길 64, 105-101 (장안동, 성우스타팰리스)",서울특별시 동대문구 서희,별점\n4.36
12,12,중식,신라방마라탕,마라탕,7000원,02-2212-9991,서울특별시 동대문구 천호대로79길 66 (장안동),서울특별시 동대문구 천호대로79길 66 (장안동),서울특별시 동대문구 신라방마라탕,별점\n4.44
...,...,...,...,...,...,...,...,...,...,...
1016,1016,한식_일반,한보식당,김치찌개,7000원,02-562-0276,서울특별시 강남구 남부순환로 2921 남서울지하상가 11호,서울특별시 강남구 남부순환로 2921 남서울지하상가 11호,서울특별시 강남구 한보식당,별점\n4.29
1017,1017,한식_일반,시골청국장,청국장,8000원,02-548-0171,서울특별시 강남구 학동로 504 서울빌딩 101호,서울특별시 강남구 학동로 504 서울빌딩 101호,서울특별시 강남구 시골청국장,별점\n4.47
1018,1018,한식_일반,해남식당,청국장,8000원,02-543-9660,서울특별시 강남구 학동로101길 26 청담삼익상가 지하1층 4호,서울특별시 강남구 학동로101길 26 청담삼익상가 지하1층 4호,서울특별시 강남구 해남식당,별점\n4.39
1019,1019,한식_일반,지리산,닭곰탕,9000원,02-546-3127,서울특별시 강남구 학동로43길 7 지상1층,서울특별시 강남구 학동로43길 7 지상1층,서울특별시 강남구 지리산,별점\n4.18
1021,1021,한식_육류,청송숯불화로구이,돼지갈비(250g),20000원,02-549-3739,서울특별시 강남구 언주로 114길 17,서울특별시 강남구 언주로 114길 17,서울특별시 강남구 청송숯불화로구이,별점\n4.52

In [223]:
df2['별점'] =df2['별점'].apply(lambda x: x.split('\n')[1])
df2

C:\Users\GJ\AppData\Local\Temp\ipykernel_14296\3522744751.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['별점'] =df2['별점'].apply(lambda x: x.split('\n')[1])

,Unnamed: 0,업종,업소명,주요품목,가격,연락처,주소,수정주소,검색어,별점
0,0,한식_육류,신원식당,삼겹살,16000원,02-3394-5121,"서울특별시 동대문구 장한로 92, 101호 (장안동, 화성빌딩)","서울특별시 동대문구 장한로 92, 101호 (장안동, 화성빌딩)",서울특별시 동대문구 신원식당,4.78
2,2,한식_일반,북한산 손칼국수,손칼국수,5500원,0507-1407-4413,서울특별시 은평구 서울특별시 은평구 대서문길36,서울특별시 은평구 대서문길36,서울특별시 은평구 북한산 손칼국수,4.32
3,3,한식_일반,응암칼국수,삼겹순대국,8000원,02-918-6700,서울특별시 은평구 서울특별시 은평구 응암로21길 18-1,서울특별시 은평구 응암로21길 18-1,서울특별시 은평구 응암칼국수,4.35
11,11,중식,서희,자장면(현금),4500원,02-2212-8877,"서울특별시 동대문구 사가정로23길 64, 105-101 (장안동, 성우스타팰리스)","서울특별시 동대문구 사가정로23길 64, 105-101 (장안동, 성우스타팰리스)",서울특별시 동대문구 서희,4.36
12,12,중식,신라방마라탕,마라탕,7000원,02-2212-9991,서울특별시 동대문구 천호대로79길 66 (장안동),서울특별시 동대문구 천호대로79길 66 (장안동),서울특별시 동대문구 신라방마라탕,4.44
...,...,...,...,...,...,...,...,...,...,...
1016,1016,한식_일반,한보식당,김치찌개,7000원,02-562-0276,서울특별시 강남구 남부순환로 2921 남서울지하상가 11호,서울특별시 강남구 남부순환로 2921 남서울지하상가 11호,서울특별시 강남구 한보식당,4.29
1017,1017,한식_일반,시골청국장,청국장,8000원,02-548-0171,서울특별시 강남구 학동로 504 서울빌딩 101호,서울특별시 강남구 학동로 504 서울빌딩 101호,서울특별시 강남구 시골청국장,4.47
1018,1018,한식_일반,해남식당,청국장,8000원,02-543-9660,서울특별시 강남구 학동로101길 26 청담삼익상가 지하1층 4호,서울특별시 강남구 학동로101길 26 청담삼익상가 지하1층 4호,서울특별시 강남구 해남식당,4.39
1019,1019,한식_일반,지리산,닭곰탕,9000원,02-546-3127,서울특별시 강남구 학동로43길 7 지상1층,서울특별시 강남구 학동로43길 7 지상1층,서울특별시 강남구 지리산,4.18
1021,1021,한식_육류,청송숯불화로구이,돼지갈비(250g),20000원,02-549-3739,서울특별시 강남구 언주로 114길 17,서울특별시 강남구 언주로 114길 17,서울특별시 강남구 청송숯불화로구이,4.52

In [221]:
df[df['별점'].str.contains('별점\n')]['별점'].apply(lambda x: x.split('\n')[1])

0       4.78
2       4.32
3       4.35
11      4.36
12      4.44
        ...
1016    4.29
1017    4.47
1018    4.39
1019    4.18
1021    4.52
Name: 별점, Length: 539, dtype: object

In [224]:
df2.drop('Unnamed: 0', axis = 1, inplace = True)

C:\Users\GJ\AppData\Local\Temp\ipykernel_14296\3227666491.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.drop('Unnamed: 0', axis = 1, inplace = True)

In [225]:
Seoulscore_naver = df2

In [202]:
Ulsanscore.to_csv('Ulsanscore.csv',index = False, encoding = 'utf-8-sig')

In [226]:
Seoulscore_naver

,업종,업소명,주요품목,가격,연락처,주소,수정주소,검색어,별점
0,한식_육류,신원식당,삼겹살,16000원,02-3394-5121,"서울특별시 동대문구 장한로 92, 101호 (장안동, 화성빌딩)","서울특별시 동대문구 장한로 92, 101호 (장안동, 화성빌딩)",서울특별시 동대문구 신원식당,4.78
2,한식_일반,북한산 손칼국수,손칼국수,5500원,0507-1407-4413,서울특별시 은평구 서울특별시 은평구 대서문길36,서울특별시 은평구 대서문길36,서울특별시 은평구 북한산 손칼국수,4.32
3,한식_일반,응암칼국수,삼겹순대국,8000원,02-918-6700,서울특별시 은평구 서울특별시 은평구 응암로21길 18-1,서울특별시 은평구 응암로21길 18-1,서울특별시 은평구 응암칼국수,4.35
11,중식,서희,자장면(현금),4500원,02-2212-8877,"서울특별시 동대문구 사가정로23길 64, 105-101 (장안동, 성우스타팰리스)","서울특별시 동대문구 사가정로23길 64, 105-101 (장안동, 성우스타팰리스)",서울특별시 동대문구 서희,4.36
12,중식,신라방마라탕,마라탕,7000원,02-2212-9991,서울특별시 동대문구 천호대로79길 66 (장안동),서울특별시 동대문구 천호대로79길 66 (장안동),서울특별시 동대문구 신라방마라탕,4.44
...,...,...,...,...,...,...,...,...,...
1016,한식_일반,한보식당,김치찌개,7000원,02-562-0276,서울특별시 강남구 남부순환로 2921 남서울지하상가 11호,서울특별시 강남구 남부순환로 2921 남서울지하상가 11호,서울특별시 강남구 한보식당,4.29
1017,한식_일반,시골청국장,청국장,8000원,02-548-0171,서울특별시 강남구 학동로 504 서울빌딩 101호,서울특별시 강남구 학동로 504 서울빌딩 101호,서울특별시 강남구 시골청국장,4.47
1018,한식_일반,해남식당,청국장,8000원,02-543-9660,서울특별시 강남구 학동로101길 26 청담삼익상가 지하1층 4호,서울특별시 강남구 학동로101길 26 청담삼익상가 지하1층 4호,서울특별시 강남구 해남식당,4.39
1019,한식_일반,지리산,닭곰탕,9000원,02-546-3127,서울특별시 강남구 학동로43길 7 지상1층,서울특별시 강남구 학동로43길 7 지상1층,서울특별시 강남구 지리산,4.18
1021,한식_육류,청송숯불화로구이,돼지갈비(250g),20000원,02-549-3739,서울특별시 강남구 언주로 114길 17,서울특별시 강남구 언주로 114길 17,서울특별시 강남구 청송숯불화로구이,4.52